### ISSUE TITLE
Select technologies 

### ISSUE THREAD

**Issue by EmadAghaei** [devuxd/devx.cs.gmu.edu#1]
What technology do you think is suitable for the website? Why do you suggest that technology?

**Comment by SaharMehrpour** [comment]
I'm not aware of many technologies. 
I propose [Jekyll](https://jekyllrb.com/) in which the content is added through markdown files.

**Comment by MaryamArab** [comment]
React, easy, fast setup. Easy maintenance.
it might have different learning curves for different members, but I guess it worth it.

**Comment by Alaboudi1** [comment]
Found  some lists of free templates
https://github.com/website-templates

https://pages.github.com/themes/

**Comment by luminaxster** [comment]
Check #3
