### ISSUE TITLE
FUU Project Image

### ISSUE THREAD

**Issue by SaharMehrpour** [devuxd/devx.cs.gmu.edu#29]
The [image](https://github.com/devuxd/devx.cs.gmu.edu/blob/master/docs_src/assets/img/research/FUU2.png) for Finding Unique Usages is kind of huge ( ~ 12.3 MB).
In my laptop, it takes some time to be rendered.
Is it possible to reduce the size of the image ( e.g., less than  500 KB )?

**Comment by luminaxster** [comment]
The simplest option on Mac is to take a screenshot of it =P

**Comment by Alaboudi1** [comment]
Yep, this image makes the website slow to render when scrolling. cc @eaghayi

**Comment by EmadAghaei** [comment]
Good catch. 
Sorry! I'll fix it.

**Comment by EmadAghaei** [comment]
Could you please look at my PR. If it is fine merge it.

**Comment by luminaxster** [comment]
fixed on #32
