### ISSUE TITLE
Customize CSS styles to match Aziz's draft

### ISSUE THREAD

**Issue by luminaxster** [devuxd/devx.cs.gmu.edu#4]
we can customize our website using this [guide](https://github.com/jekyll/minima#customizing-templates). Alternatively, we can change the theme anytime to something from https://jekyllthemes.io/, for example: bulma-clean-theme.
Let's list the changes we want to make:
- Add devX icon
...

**Comment by SaharMehrpour** [comment]
About the style. How about using our own styling (using bootstrap and other libraries of course) to have more flexibility?

**Comment by luminaxster** [comment]
Sure, maybe this guide can help: https://github.com/sparkrnyc/sparkr_general_docs/wiki/How-to-Add-Bootstrap-to-Jekyll

**Comment by SaharMehrpour** [comment]
What is the downside of importing bootstrap in the `head` of the HTML files? 
I'm working on the layouts and tried importing bootstrap and CSS files in the head of HTML files. It works. Of course, I had to remove the theme from`_config.yml`.

**Comment by luminaxster** [comment]
You don't have to remove the theme to add Bootstrap, we can [customize it](https://github.com/jekyll/minima#customizing-templates). We only have to put in `_layouts` the elements we want to customize (e.g. `head.html`), we get the original from the minima repo and paste it `_layouts`. The theme will process our layout files instead of theirs.

**Comment by Alaboudi1** [comment]
I have a question, can we just use the style that was in the first design and build on top of it? It has bootstrap and other useful libraries.  Can we just drag and drop existing CSS and it just works?

**Comment by SaharMehrpour** [comment]
I am doing something like this:
https://github.com/luminaxster/devx.cs.gmu.edu/pull/2/files#diff-37357a8d5a81de465abf59b6cdf46946R1

I will send out a pull request later tonight. If you like that (structure and implementation), we can continue with improving the style.

**Comment by Alaboudi1** [comment]
Cool. I would appreciate it if you also write some documentation on how the code works.
