### ISSUE TITLE
Profile Pages and Project Pages?

### ISSUE THREAD

**Issue by SaharMehrpour** [devuxd/devx.cs.gmu.edu#5]
What do you think about having profile pages for each member of the lab?
I am thinking of putting information of publications, news, images, and maybe a bio?

How about having a dedicated Project Page for each project? Is it too much?
I am thinking of showing a brief description of a project, demo videos (if any), collaborators, publications, artifacts (like source code, and study material)

**Comment by luminaxster** [comment]
I concur with all your points, Sahar. Structurally, we should create a new repo for individual website templates forked from this repo, then we add a link in this project for each personal web page. I don't think having a website for each project is too much to ask, we enable GH pages in their repos and they are ready to go(e.g. this repo https://github.com/luminaxster/swe432tomcat has GH-pages enabled in 2 clicks: https://luminaxster.github.io/swe432tomcat/). For consistency, we should all agree on a theme that can be used across all pages.
